export const driverImages: Record<string, string> = {
  albon: "/drivers/albon.png",
  alonso: "/drivers/alonso.png",
  antonelli: "/drivers/antonelli.png",
  bearman: "/drivers/bearman.png",
  bortoleto: "/drivers/bortoleto.png",
  bottas: "/drivers/bottas.png",
  colapinto: "/drivers/colapinto.png",
  gasly: "/drivers/gasly.png",
  hadjar: "/drivers/hadjar.png",
  hamilton: "/drivers/hamilton.png",
  hulkenberg: "/drivers/hulkenberg.png",
  lawson: "/drivers/lawson.png",
  leclerc: "/drivers/leclerc.png",
  norris: "/drivers/norris.png",
  ocon: "/drivers/ocon.png",
  piastri: "/drivers/piastri.png",
  perez: "/drivers/perez.png",
  russell: "/drivers/russell.png",
  sainz: "/drivers/sainz.png",
  stroll: "/drivers/stroll.png",
  tsunoda: "/drivers/tsunoda.png",
  max_verstappen: "/drivers/max_verstappen.png",
  arvid_lindblad: "/drivers/arvid_lindblad.png",
};
